# Generated by Django 5.2 on 2025-04-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SportFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sport_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('capacity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
