# Generated by Django 5.2 on 2025-04-26 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sportfacility',
            options={'verbose_name_plural': 'Sport Facilities'},
        ),
    ]
