# Generated by Django 5.2 on 2025-04-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_facilitytype_alter_sportfacility_sport_type_pricing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportfacility',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='sport_facilities/'),
        ),
    ]
